[build]
    publish = "public"
    command = "hugo --gc --minify"

[context.production.environment]
    HUGO_VERSION = "0.74.3"
    HUGO_ENV = "production"
    HUGO_ENABLEGITINFO = "true"

[[plugins]]
    package = "netlify-plugin-hugo-cache-resources"

[[headers]]
    for = "/*"
    [headers.values]
        Content-Security-Policy =  "default-src 'none'; script-src 'self'; style-src 'self'; img-src 'self'; media-src 'self'; manifest-src 'self'"
        Referrer-Policy = "strict-origin-when-cross-origin"
        X-Content-Type-Options = "nosniff"
        X-Frame-Options = "DENY"
[[headers]]
    for = "/*.xml"
    [headers.values]
        Content-Security-Policy =  "style-src 'unsafe-inline';"
        X-Content-Type-Options = ""
